### PR TITLE
Fix tabs web components nested tabs issues

### PR DESCRIPTION
**Pull request by KhokanTP**
Fixed: https://github.com/Travelopia/web-components/issues/72

This PR fixes the nested tabs display content and current tab assignment issues on click nested tabs or parent tabs and vice versa.

### CODE REVIEW

**Comment by junaidbhura** [comment]
@sagarjadhav can you please review this?

**Review by sagarjadhav — APPROVED** [review]

**Comment by sagarjadhav** [comment]
@junaidbhura The above PR looks good and fix the issue. Can you please review and merge?

**Comment by junaidbhura** [comment]
Thanks @sagarjadhav @KhokanTP - how many levels of nesting does this take care of?

**Comment by KhokanTP** [comment]
> Thanks @sagarjadhav @KhokanTP - how many levels of nesting does this take care of?

@junaidbhura it should take care of nth levels though I have tested with 4th levels of nesting only with this PR.

**Review by junaidbhura — APPROVED** [review]

**Pull request merged**
