### PR TITLE
Fix Slider Next action when per-view is added

### PR DESCRIPTION
**Pull request by junaidbhura**
Fix Slider Next action when per-view is added.

### CODE REVIEW

**Review by benerd — APPROVED** [review]

**Comment by junaidbhura** [comment]
Thanks @benerd have you tested this on ET?

**Review by imranhsayed — APPROVED** [review]

**Comment by harshdeep-gill** [comment]
The issue this PR addresses occurs when the per-view attribute is set to a value greater than 1. While navigating to the last item by pressing the next button, the current logic only checks if the current slide index is on the last item before stopping the slide.

However, with a per-view value (e.g., 2), the last item is already in view when the current slide index is on the second-to-last item. Therefore, the slider should not continue advancing. Currently, this results in empty spaces appearing at the end of the slider.

https://github.com/user-attachments/assets/efd6e647-a4da-4167-98f9-a6582184b4b8

**Comment by sagarjadhav** [comment]
@harshdeep-gill Can you please provide the sample usage code with settings?

**Comment by sagarjadhav** [comment]
@harshdeep-gill Thanks for the call. As per the discussion and findings we need to fix following issues.
- Need to add disable attributes to Previous and Next buttons when slides end.
- Pagination should work properly with the steps.

cc: @junaidbhura

**Review by sagarjadhav — CHANGES_REQUESTED** [review]
@harshdeep-gill Thanks for the call. As per the discussion and findings we need to fix following issues.

Need to add disable attributes to Previous and Next buttons when slides end.
Pagination should work properly with the steps.
cc: @junaidbhura

**Comment by harshdeep-gill** [comment]
Hi @sagarjadhav , As discussed there were two more issues that aroused with fixing the per-view issue - those were, slider-nav buttons were not in sync with step variable and while moving to the last image next button was not getting the disabled:"yes" attribute. In the latest commit these two issues are being fixed.
cc: @junaidbhura

**Review by sagarjadhav — APPROVED** [review]
Looks good.

**Pull request merged**
